function [tdt2adapterMap, adapter2cereportMap, cereport2arrayMap,array2anotomyMap,tdt2arrayMap,tdt2anatomyMap] = getMaps(config)

%% TDT 2 Adapter
    switch config
        case 'earlRH_LGAOmnetics_FlexConnector'
            adapter2TDTTable = readtable('earlRHArrayMap.xlsx','Range','AF3:AH131');
            adapterBank = adapter2TDTTable{:,1}; 
            adapterPin = num2str(adapter2TDTTable{:,2},'%02u');
            TDTchannel = adapter2TDTTable{:,3};
            adapter2tdtMap = cell(size(adapter2TDTTable,1),2);
            for i = 1:size(adapter2tdtMap,1)
               adapter2tdtMap{i,1} = [adapterBank{i,:},adapterPin(i,:)]; 
               adapter2tdtMap{i,2} = TDTchannel(i,:); 
            end
            
        case 'earlRH_LGAOmnetics'
            adapter2TDTTable = readtable('earlRHArrayMap.xlsx','Range','T3:V131');
            adapterBank = adapter2TDTTable{:,1}; 
            adapterPin = num2str(adapter2TDTTable{:,2},'%02u');
            TDTchannel = adapter2TDTTable{:,3};
            adapter2tdtMap = cell(size(adapter2TDTTable,1),2);
            for i = 1:size(adapter2tdtMap,1)
               adapter2tdtMap{i,1} = [adapterBank{i,:},adapterPin(i,:)]; 
               adapter2tdtMap{i,2} = TDTchannel(i,:); 
            end
            
        case {'prezLHPMd','prezLHM1','earlRHM1','earlRHPMd'}
            adapter2tdtMap = { ...
                'A01', 49; ...
                'A02', 51; ...
                'A03', 53; ...
                'A04', 55; ...
                'A05', 57; ...
                'A06', 59; ...
                'A07', 61; ...
                'A08', 63; ...
                'A09', 65; ...
                'A10', 67; ...
                'A11', 69; ...
                'A12', 71; ...
                'A13', 50; ...
                'A14', 52; ...
                'A15', 54; ...
                'A16', 56; ...
                'A17', 58; ...
                'A18', 60; ...
                'A19', 62; ...
                'A20', 64; ...
                'A21', 66; ...
                'A22', 68; ...
                'A23', 70; ...
                'A24', 72; ...
                'A25', 74; ...
                'A26', 76; ...
                'A27', 78; ...
                'A28', 80; ...
                'A29', 82; ...
                'A30', 84; ...
                'A31', 86; ...
                'A32', 88; ...
                'B01', 90; ...
                'B02', 92; ...
                'B03', 94; ...
                'B04', 96; ...
                'B05', 73; ...
                'B06', 75; ...
                'B07', 77; ...
                'B08', 79; ...
                'B09', 81; ...
                'B10', 83; ...
                'B11', 85; ...
                'B12', 87; ...
                'B13', 89; ...
                'B14', 91; ...
                'B15', 93; ...
                'B16', 95; ...
                'B17', 1; ...
                'B18', 3; ...
                'B19', 5; ...
                'B20', 7; ...
                'B21', 9; ...
                'B22', 11; ...
                'B23', 13; ...
                'B24', 15; ...
                'B25', 17; ...
                'B26', 19; ...
                'B27', 21; ...
                'B28', 23; ...
                'B29', 2; ...
                'B30', 4; ...
                'B31', 6; ...
                'B32', 8; ...
                'C01', 10; ...
                'C02', 12; ...
                'C03', 14; ...
                'C04', 16; ...
                'C05', 18; ...
                'C06', 20; ...
                'C07', 22; ...
                'C08', 24; ...
                'C09', 26; ...
                'C10', 28; ...
                'C11', 30; ...
                'C12', 32; ...
                'C13', 34; ...
                'C14', 36; ...
                'C15', 38; ...
                'C16', 40; ...
                'C17', 42; ...
                'C18', 44; ...
                'C19', 46; ...
                'C20', 48; ...
                'C21', 25; ...
                'C22', 27; ...
                'C23', 29; ...
                'C24', 31; ...
                'C25', 33; ...
                'C26', 35; ...
                'C27', 37; ...
                'C28', 39; ...
                'C29', 41; ...
                'C30', 43; ...
                'C31', 45; ...
                'C32', 47};  
    end
    
    tdt2adapterMap = adapter2tdtMap;
    tdt2adapterMap(:,1) = adapter2tdtMap(:,2);
    tdt2adapterMap(:,2) = adapter2tdtMap(:,1);
    [~,sortInd] = sort(cell2mat(tdt2adapterMap(:,1)));
    tdt2adapterMap = tdt2adapterMap(sortInd,:); 
    
%% Adapter 2 cereport map
    %Get map data 
    switch config
        case 'prezLHPMd'
            adapter2CereportTable = readtable('cereport2zifClipMappingForPrezChokingLH.xlsx','Range','A1:E145');
            adapterBank = adapter2CereportTable{:,3};
            adapterPin = num2str(adapter2CereportTable{:,5},'%02u');
            cereportBank = adapter2CereportTable{:,1};
            cereportPin = num2str(adapter2CereportTable{:,2},'%02u');
        case 'prezLHM1'
            adapter2CereportTable = readtable('cereport2zifClipMappingForPrezChokingLH.xlsx','Range','A1:E145');
            adapterBank = adapter2CereportTable{:,4}; 
            adapterPin = num2str(adapter2CereportTable{:,5},'%02u');
            cereportBank = adapter2CereportTable{:,1};
            cereportPin = num2str(adapter2CereportTable{:,2},'%02u');
        case {'earlRH_LGAOmnetics','earlRH_LGAOmnetics_FlexConnector'}
            adapter2CereportTable = readtable('earlRHArrayMap.xlsx','Range','R3:U131');
            adapterBank = adapter2CereportTable{:,3}; 
            adapterPin = num2str(adapter2CereportTable{:,4},'%02u');
            cereportBank = adapter2CereportTable{:,1};
            cereportPin = num2str(adapter2CereportTable{:,2},'%02u');
        case 'earlRHM1'
            adapter2CereportTable = readtable('earlRHArrayMap.xlsx','Range','W3:Z147');
            adapterBank = adapter2CereportTable{:,3}; 
            adapterPin = num2str(adapter2CereportTable{:,4},'%02u');
            cereportBank = adapter2CereportTable{:,1};
            cereportPin = num2str(adapter2CereportTable{:,2},'%02u');
        case 'earlRHPMd'
            adapter2CereportTable = readtable('earlRHArrayMap.xlsx','Range','AB3:AE147');
            adapterBank = adapter2CereportTable{:,3}; 
            adapterPin = num2str(adapter2CereportTable{:,4},'%02u');
            cereportBank = adapter2CereportTable{:,1};
            cereportPin = num2str(adapter2CereportTable{:,2},'%02u');
            
    end
    
    %Create map cell
    switch config
        case {'prezLHPMd','prezLHM1','earlRHM1','earlRHPMd','earlRH_LGAOmnetics','earlRH_LGAOmnetics_FlexConnector'}
            adapter2cereportMap = cell(size(adapter2CereportTable,1),2);
            for i = 1:size(adapter2cereportMap,1)
               adapter2cereportMap{i,1} = [adapterBank{i,:},adapterPin(i,:)]; 
               adapter2cereportMap{i,2} = [cereportBank{i,:},cereportPin(i,:)]; 
            end
    end
    
%% Cereport 2 array map
    %Get table 
    switch config
        case {'prezLHM1', 'prezLHPMd'}
            cereport2arrayTable = readtable('prezLHArrayMap.xlsx','Range','C2:D130');
        case {'earlRHM1','earlRHPMd','earlRH_LGAOmnetics','earlRH_LGAOmnetics_FlexConnector'}
            cereport2arrayTable = readtable('earlRHArrayMap.xlsx','Range','C2:D130');
    end
    
    %Create map
    switch config
        case {'prezLHM1','prezLHPMd','earlRHM1','earlRHPMd','earlRH_LGAOmnetics','earlRH_LGAOmnetics_FlexConnector'}
            cereport2arrayMap = cell(128,2);
            cereportBank = cereport2arrayTable{:,1};
            cereportPin = cereport2arrayTable{:,2};
            arrayElectrode = [128:-1:1]';
            for i = 1:128
               cereport2arrayMap{i,1} =  [cereportBank{i,:},num2str(str2num(cereportPin{i,:}),'%02u')]; 
               cereport2arrayMap{i,2} = arrayElectrode(i,1);
            end
    end
    
%% Array 2 anatomy map
    switch config
        case {'prezLHM1', 'prezLHPMd'}
            array2anatomyTable = readtable('prezLHArrayMap.xlsx','Range','M3:T19');
        case {'earlRH','earlRHM1','earlRHPMd','earlRH_LGAOmnetics','earlRH_LGAOmnetics_FlexConnector'}
            array2anatomyTable = readtable('earlRHArrayMap.xlsx','Range','I2:P18');
    end
    array2anotomyMap = array2anatomyTable{:,:};
            
    
%% TDT 2 anatomy map
    numChannels = size(tdt2adapterMap,1);
    tdt2arrayMap = nan(numChannels,2);
    tdt2anatomyMap = cell(numChannels,3);
    for i = 1:numChannels
        adapterPin = tdt2adapterMap{i,2};
        %replace "contains" w "matches" when you update matlab
        cereportInd = find(contains(adapter2cereportMap(:,1),adapterPin));
        cereportPin = adapter2cereportMap{cereportInd,2};
        arrayInd = find(contains(cereport2arrayMap(:,1),cereportPin));
        arrayPin = cereport2arrayMap{arrayInd,2};
        tdt2arrayMap(i,1) = i; tdt2arrayMap(i,2) = arrayPin;
        tdt2anatomyMap{i,1} = i;
        [row,col] = find(table2array(array2anatomyTable) == arrayPin);
        tdt2anatomyMap{i,2} = row;
        tdt2anatomyMap{i,3} = col;
    end    
end